// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YourRhythmStudio.Infrastructure.Data;

#nullable disable

namespace YourRhythmStudio.Migrations
{
    [DbContext(typeof(YourRhythmDbContext))]
    [Migration("20260708013410_AddSchoolPlanCode")]
    partial class AddSchoolPlanCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("YourRhythmStudio.Domain.Learning.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime?>("DueAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("RepertoireItemId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("char(36)");

                    b.Property<int>("TargetMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("TeacherProfileId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("XpGranted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("XpReward")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("RepertoireItemId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("TeacherProfileId");

                    b.HasIndex("SchoolId", "StudentProfileId", "Status");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("YourRhythmStudio.Domain.Learning.FeedbackEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssignmentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<Guid?>("RepertoireItemId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TeacherProfileId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("VisibleToStudent")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("LessonId");

                    b.HasIndex("RepertoireItemId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("TeacherProfileId");

                    b.HasIndex("SchoolId", "StudentProfileId", "VisibleToStudent");

                    b.ToTable("feedback_entries", (string)null);
                });

            modelBuilder.Entity("YourRhythmStudio.Domain.Learning.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LessonDateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TeacherProfileId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("TeacherProfileId");

                    b.HasIndex("SchoolId", "StudentProfileId", "LessonDateUtc");

                    b.ToTable("lessons", (string)null);
                });

            modelBuilder.Entity("YourRhythmStudio.Domain.Learning.RepertoireItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ComposerOrArtist")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Instrument")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Level")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TeacherProfileId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("TeacherProfileId");

                    b.HasIndex("SchoolId", "StudentProfileId", "Status");

                    b.ToTable("repertoire_items", (string)null);
                });

            modelBuilder.Entity("YourRhythmStudio.Domain.Learning.TeacherStudent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeactivatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TeacherProfileId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("TeacherProfileId");

                    b.HasIndex("SchoolId", "TeacherProfileId", "StudentProfileId")
                        .IsUnique();

                    b.ToTable("teacher_students", (string)null);
                });

            modelBuilder.Entity("YourRhythmStudio.Domain.Learning.XpEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TeacherProfileId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("SourceId");

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("TeacherProfileId");

                    b.HasIndex("SchoolId", "StudentProfileId", "CreatedAtUtc");

                    b.ToTable("xp_events", (string)null);
                });

            modelBuilder.Entity("YourRhythmStudio.Domain.Users.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<Guid?>("OwnerAccountId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasDefaultValue("professor");

                    b.Property<string>("PrimaryEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("schools", (string)null);
                });

            modelBuilder.Entity("YourRhythmStudio.Domain.Users.SchoolUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Email")
                        .IsUnique();

                    b.ToTable("school_users", (string)null);
                });

            modelBuilder.Entity("YourRhythmStudio.Domain.Users.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("int");

                    b.Property<int>("CurrentXp")
                        .HasColumnType("int");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SchoolUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("SchoolUserId")
                        .IsUnique();

                    b.ToTable("student_profiles", (string)null);
                });

            modelBuilder.Entity("YourRhythmStudio.Domain.Users.TeacherProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("CanManageStudents")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("InstrumentFocus")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SchoolUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("SchoolUserId")
                        .IsUnique();

                    b.ToTable("teacher_profiles", (string)null);
                });

            modelBuilder.Entity("YourRhythmStudio.Infrastructure.Data.PersistedAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PlatformRole")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("PwdAlgorithm")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("PwdHashBase64")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int>("PwdIterations")
                        .HasColumnType("int");

                    b.Property<string>("PwdSaltBase64")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("PwdUpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("persisted_accounts", (string)null);
                });

            modelBuilder.Entity("YourRhythmStudio.Domain.Learning.Assignment", b =>
                {
                    b.HasOne("YourRhythmStudio.Domain.Learning.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("YourRhythmStudio.Domain.Learning.RepertoireItem", null)
                        .WithMany()
                        .HasForeignKey("RepertoireItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("YourRhythmStudio.Domain.Users.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YourRhythmStudio.Domain.Users.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YourRhythmStudio.Domain.Users.TeacherProfile", null)
                        .WithMany()
                        .HasForeignKey("TeacherProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourRhythmStudio.Domain.Learning.FeedbackEntry", b =>
                {
                    b.HasOne("YourRhythmStudio.Domain.Learning.Assignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("YourRhythmStudio.Domain.Learning.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("YourRhythmStudio.Domain.Learning.RepertoireItem", null)
                        .WithMany()
                        .HasForeignKey("RepertoireItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("YourRhythmStudio.Domain.Users.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YourRhythmStudio.Domain.Users.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YourRhythmStudio.Domain.Users.TeacherProfile", null)
                        .WithMany()
                        .HasForeignKey("TeacherProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourRhythmStudio.Domain.Learning.Lesson", b =>
                {
                    b.HasOne("YourRhythmStudio.Domain.Users.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YourRhythmStudio.Domain.Users.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YourRhythmStudio.Domain.Users.TeacherProfile", null)
                        .WithMany()
                        .HasForeignKey("TeacherProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourRhythmStudio.Domain.Learning.RepertoireItem", b =>
                {
                    b.HasOne("YourRhythmStudio.Domain.Users.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YourRhythmStudio.Domain.Users.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YourRhythmStudio.Domain.Users.TeacherProfile", null)
                        .WithMany()
                        .HasForeignKey("TeacherProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourRhythmStudio.Domain.Learning.TeacherStudent", b =>
                {
                    b.HasOne("YourRhythmStudio.Domain.Users.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YourRhythmStudio.Domain.Users.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YourRhythmStudio.Domain.Users.TeacherProfile", null)
                        .WithMany()
                        .HasForeignKey("TeacherProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourRhythmStudio.Domain.Learning.XpEvent", b =>
                {
                    b.HasOne("YourRhythmStudio.Domain.Users.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YourRhythmStudio.Domain.Users.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YourRhythmStudio.Domain.Users.TeacherProfile", null)
                        .WithMany()
                        .HasForeignKey("TeacherProfileId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("YourRhythmStudio.Domain.Users.SchoolUser", b =>
                {
                    b.HasOne("YourRhythmStudio.Domain.Users.School", "School")
                        .WithMany("Users")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("YourRhythmStudio.Domain.Users.StudentProfile", b =>
                {
                    b.HasOne("YourRhythmStudio.Domain.Users.School", "School")
                        .WithMany("Students")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YourRhythmStudio.Domain.Users.SchoolUser", "SchoolUser")
                        .WithOne()
                        .HasForeignKey("YourRhythmStudio.Domain.Users.StudentProfile", "SchoolUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("SchoolUser");
                });

            modelBuilder.Entity("YourRhythmStudio.Domain.Users.TeacherProfile", b =>
                {
                    b.HasOne("YourRhythmStudio.Domain.Users.School", "School")
                        .WithMany("Teachers")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YourRhythmStudio.Domain.Users.SchoolUser", "SchoolUser")
                        .WithOne()
                        .HasForeignKey("YourRhythmStudio.Domain.Users.TeacherProfile", "SchoolUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("SchoolUser");
                });

            modelBuilder.Entity("YourRhythmStudio.Domain.Users.School", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Teachers");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
